# Generated by Django 4.1 on 2023-11-19 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0002_file_savedtext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedtext',
            name='file',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='SavedText',
        ),
    ]
